# Tugas 2



*   Carilah data yang bertipe numerik ( data klasifikasi)

  *   Lakukan proses diskritisasi dengan equal width dan equal frequency

  *   Lakukan proses diskritisasi  dengan basis entropy

## Import Dataset dari GitHub

In [ ]:
import math
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None 
data = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
data

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

## Distraksi

Distraksi merupakan transformasi kolom menjadi type data lain. Tujuannya untuk membuat data menjadi lebih optimal yang nantinya memudahkan untuk di analisis

## Equal-Width Interval

Equal-width intervals adalah distraksi yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar.

Rumus untuk membagi kedalam k interval
\begin{align}
        w = \frac {(max -min)}{b}
\end{align}

Rumus untuk mencari batasan
\begin{align}
        min+w, min+2w, ... , min+(k-1)w
\end{align}

Mengambil sampel data

In [ ]:
sepal_length = data[["sepal.length"]]
sepal_width = data[["sepal.width"]]
petal_length = data[["petal.length"]]
petal_width = data[["petal.width"]]

Mencari interval menggunakan metode Equal-Width Interval dengan Pandas

In [ ]:
def cut(col, k):
    intervals = pd.cut(data[col], k).value_counts().index.to_list()
    return [[interval.left, interval.right] for interval in intervals]

In [ ]:
def toCategory(list_interval, col):
    # get length interval
    length = len(list_interval)

    # Sorting interval
    sort_interval = np.sort(list_interval, axis=0)
    # Get Category from interval
    categories = np.array([chr(65+i) for i in range(length)])[:, None]
    # combine into interval data
    intervals = np.hstack((sort_interval, categories))

    # Operate All data
    newCol = []
    for i, row in data.iterrows():
        datas = row[col]
        for interval in intervals:
            if datas >= interval[0].astype(float) and datas <= interval[1].astype(float):
                newCol.append(interval[2])
                break
    # return new coloumn category
    return np.array(newCol, dtype=str)

Membagi interval menjadi 4 bagian

In [ ]:
interval_sepal_length = cut("sepal.length", 4)
interval_sepal_width = cut("sepal.width", 4)
interval_petal_length = cut("petal.length", 4)
interval_petal_width = cut("petal.width", 4)

print("interval sepal.length :", interval_sepal_length)
print("interval sepal.width  :", interval_sepal_width)
print("interval petal.length :", interval_petal_length)
print("interval petal.width  :", interval_petal_width)

interval sepal.length : [[5.2, 6.1], [4.296, 5.2], [6.1, 7.0], [7.0, 7.9]]
interval sepal.width  : [[2.6, 3.2], [3.2, 3.8], [1.998, 2.6], [3.8, 4.4]]
interval petal.length : [[3.95, 5.425], [0.994, 2.475], [5.425, 6.9], [2.475, 3.95]]
interval petal.width  : [[0.0976, 0.7], [1.3, 1.9], [1.9, 2.5], [0.7, 1.3]]

Menampilkan hasil dari pembagian kategori

In [ ]:
sepal_length["category"] = toCategory(interval_sepal_length, "sepal.length")
sepal_width["category"] = toCategory(interval_sepal_width, "sepal.width")
petal_length["category"] = toCategory(interval_petal_length, "petal.length")
petal_width["category"] = toCategory(interval_petal_width, "petal.width")

display(sepal_length)
display(sepal_width)
display(petal_length)
display(petal_width)

     sepal.length category
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        C
146           6.3        C
147           6.5        C
148           6.2        C
149           5.9        B

[150 rows x 2 columns]

     sepal.width category
0            3.5        C
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        C
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        C
149          3.0        B

[150 rows x 2 columns]

     petal.length category
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     petal.width category
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        D
146          1.9        C
147          2.0        D
148          2.3        D
149          1.8        C

[150 rows x 2 columns]

## Equal-Frequency Interval

Equal-frequency intervals adalah distraksi yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

In [ ]:
sepal_length = data[["sepal.length"]]
sepal_width = data[["sepal.width"]]
petal_length = data[["petal.length"]]
petal_width = data[["petal.width"]]

Mencari interval menggunakan metode Equal-Frequency Interval dengan qcut Pandas

In [ ]:
def qcut(col, k):
    intervals = pd.qcut(data[col], k).value_counts().index.to_list()
    return [[interval.left, interval.right] for interval in intervals]

Membagi data menjadi 4 bagian

In [ ]:
interval_sepal_length = qcut("sepal.length", 4)
interval_sepal_width = qcut("sepal.width", 4)
interval_petal_length = qcut("petal.length", 4)
interval_petal_width = qcut("petal.width", 4)

print("interval sepal.length :", interval_sepal_length)
print("interval sepal.width  :", interval_sepal_width)
print("interval petal.length :", interval_petal_length)
print("interval petal.width  :", interval_petal_width)

interval sepal.length : [[4.2989999999999995, 5.1], [5.1, 5.8], [5.8, 6.4], [6.4, 7.9]]
interval sepal.width  : [[1.999, 2.8], [3.3, 4.4], [2.8, 3.0], [3.0, 3.3]]
interval petal.length : [[0.999, 1.6], [4.35, 5.1], [5.1, 6.9], [1.6, 4.35]]
interval petal.width  : [[0.099, 0.3], [1.3, 1.8], [0.3, 1.3], [1.8, 2.5]]

Hasil Pembagian Kategori

In [ ]:
sepal_length["category"] = toCategory(interval_sepal_length, "sepal.length")
sepal_width["category"] = toCategory(interval_sepal_width, "sepal.width")
petal_length["category"] = toCategory(interval_petal_length, "petal.length")
petal_width["category"] = toCategory(interval_petal_width, "petal.width")

display(sepal_length)
display(sepal_width)
display(petal_length)
display(petal_width)

     sepal.length category cateogry
0             5.1        A        A
1             4.9        A        A
2             4.7        A        A
3             4.6        A        A
4             5.0        A        A
..            ...      ...      ...
145           6.7        D        D
146           6.3        C        C
147           6.5        D        D
148           6.2        C        C
149           5.9        C        C

[150 rows x 3 columns]

     sepal.width category cateogry
0            3.5        D        D
1            3.0        B        B
2            3.2        C        C
3            3.1        C        C
4            3.6        D        D
..           ...      ...      ...
145          3.0        B        B
146          2.5        A        A
147          3.0        B        B
148          3.4        D        D
149          3.0        B        B

[150 rows x 3 columns]

     petal.length category cateogry
0             1.4        A        A
1             1.4        A        A
2             1.3        A        A
3             1.5        A        A
4             1.4        A        A
..            ...      ...      ...
145           5.2        D        D
146           5.0        C        C
147           5.2        D        D
148           5.4        D        D
149           5.1        C        C

[150 rows x 3 columns]

     petal.width category cateogry
0            0.2        A        A
1            0.2        A        A
2            0.2        A        A
3            0.2        A        A
4            0.2        A        A
..           ...      ...      ...
145          2.3        D        D
146          1.9        D        D
147          2.0        D        D
148          2.3        D        D
149          1.8        C        C

[150 rows x 3 columns]

## Entropy

Entropy merupakan informasi yang menggambarkan seberapa konsisten pemisah akan cocok dengan pengklasifikasi

Rumus mencari entrhopy
\begin{align}
    Entrophy = - \sum P_i log_2 p_i
\end{align}

Rumus mencari informasi
\begin{align}
    info(D_{new}) = \frac {|D_1|}{|D|} Entrophy(D_2) +  \frac {|D_2|}{|D|} Entrophy(D_2)
\end{align}

Rumus mencari gain
\begin{align}
    gain = D_{new} - D_{initial}
\end{align}

Membuat sample data

In [ ]:
sample = data[["sepal.length"]]
sample.describe()

       sepal.length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

Membuat random kategori untuk semua data

In [ ]:
np.random.seed(0)
sample["category"] = np.where(np.random.choice(2, sample.shape[0]) < 1, "A", "B" )
sample

     sepal.length category
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

Membuat fungsi getOverallCategory digunakan untuk menghitung data keseluruhan yang nantinya akan digunakan untuk menghitung entropy

In [ ]:
def getOverallCategory(col):
    group = sample.loc[:, :].groupby("category").count()
    a = group.loc["A", col]
    b = group.loc["B", col]
    return (a, b, a+b)

Fungsi splitter digunakan untuk membuat split antara value yang telah di tentukan lalu mengembalikan data yang telah dipisahkan

In [ ]:
def splitter(value:float, col:str)->tuple:
    # get data less and greater from value
    less = sample[sample[col] <= value]
    greater = sample[sample[col] > value]

    # calculate into category for each data
    less_group = less.loc[:, :].groupby("category").count()
    greater_group = greater.loc[:, :].groupby("category").count()

    # get value based on category
    less_category_A = less_group.loc["A", col]

    less_category_B = less_group.loc["B", col]
    greater_category_A = greater_group.loc["A", col]
    greater_category_B = greater_group.loc["B", col]

    return (
        [less_category_A, less_category_B, less_category_A + less_category_B],
        [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
    )

Buat Fungsi untuk mencari nilai entropy

In [ ]:
def entropy(d):
    r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
    r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
    return np.sum([r1, r2]) * -1

Membuat fungsi gain dan info. Fungsi gain untuk menghitung selsih antara entropy awal dengan yang baru

In [ ]:
def info(d):
    r1 = (d[0][2] / sample.shape[0])  * entropy(d[0])
    r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
    return r1 + r2

In [ ]:
def gain(Einitial, Enew):
    return Einitial - Enew

Dinitial

In [ ]:
D = getOverallCategory("sepal.length")
entropy_d = entropy(D)
print(D)
display(entropy_d)

(68, 82, 150)

0.993707106604508

Melakukan beberapa split untuk menemukan informasi yang terbaik

Split 1: 4.5

In [ ]:
split1 = splitter(4.5, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.0069930419733333915

Split 2: 6.5

In [ ]:
split2 = splitter(6.5, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.0069930419733333915

Split 3: 7.2

In [ ]:
split3 = splitter(7.2, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.0069930419733333915